name: test
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install npm dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:swc